services:
  _defaults:
    autowire: true
    autoconfigure: true

  Zabachok\Symfobooster\Maker\EndpointMaker:
    class: Zabachok\Symfobooster\Maker\Endpoint\EndpointMaker
    tags: ["maker.command"]
